### ISSUE TITLE
lmdb Compiled failure

### ISSUE THREAD

**Issue by litterbug23** [SakuraEngine/SakuraEngine#105]
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2017
[ 20%]: compiling.release lmdb\mdb.c
[ 20%]: compiling.release lmdb\midl.c
error: mdb.c
lmdb\mdb.c(1793): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(1793): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(1838): error C2664: “void mdb_dpage_free(MDB_env *,MDB_page *)”: 无法将参数 2 从“void *”转换为“MDB_page *”
lmdb\mdb.c(1838): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2059): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(2059): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2499): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(2499): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2555): error C2440: “=”: 无法从“void *”转换为“MDB_cursor *”
lmdb\mdb.c(2555): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2694): error C2440: “初始化”: 无法从“LPVOID”转换为“MDB_reader *”
lmdb\mdb.c(2694): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2858): error C2440: “=”: 无法从“void *”转换为“MDB_txn *”
lmdb\mdb.c(2858): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2872): error C2440: “=”: 无法从“void *”转换为“MDB_ID2L”
lmdb\mdb.c(2872): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(2955): error C2440: “初始化”: 无法从“void *”转换为“char *”
lmdb\mdb.c(2955): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3322): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(3322): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3337): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(3337): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3428): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(3428): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3720): error C2440: “=”: 无法从“void *”转换为“MDB_meta *”
lmdb\mdb.c(3720): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3783): error C2440: “=”: 无法从“void *”转换为“MDB_page *”
lmdb\mdb.c(3783): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(3953): error C2440: “=”: 无法从“void *”转换为“MDB_env *”
lmdb\mdb.c(3953): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(4011): error C2440: “=”: 无法从“LPVOID”转换为“char *”
lmdb\mdb.c(4011): note: 从“void*”到指向非“void”的指针的强制转换要求显式类型强制转换
lmdb\mdb.c(4056): error C2440: “=”: 无法从“void *”转换为“MDB_meta *”

**Comment by SaeruHikari** [comment]
看上去是把 c 文件当 cpp 文件编译了，我检查一下 lmdb 的构建脚本。

**Comment by SaeruHikari** [comment]
#108
