### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by happyxianyu** [SakuraEngine/SakuraEngine#106]
平台：win10，x64
推测原因：项目里的clang版本是14.0.0，报错信息中说要16.0.0才行，是不是该升级clang版本了？

报错信息：
```
error: In file included from D:\Bill\code\project\SakuraEngine\build\.gens\SkrAnim\windows\reflection\src\reflection_1.cpp:1:
In file included from D:\Bill\code\project\SakuraEngine\build\.gens\SkrAnim\windows\reflection\src/..\..\..\..\..\..\modules\animation\include\SkrAnim\components\skeleton_component.h:2:
In file included from modules\animation\include\SkrAnim/resources/skeleton_resource.h:11:
In file included from modules\animation\ozz\SkrAnim/ozz/skeleton.h:32:
In file included from modules\animation\ozz\SkrAnim/ozz/base/io/archive_traits.h:35:
D:\program\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals_core.h(847,1): error: static assertion failed: Error in C++ Standard Library usage.
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 16.0.0 or newer.");
```

**Comment by SaeruHikari** [comment]
这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。

升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。

（你是咋判断出是 14.0.0 的。。。

**Comment by SaeruHikari** [comment]
如果想快速解决的话装个低版本 Windows SDK 应该可以暂时绕过。

**Comment by happyxianyu** [comment]
> 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> 
> 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> 
> （你是咋判断出是 14.0.0 的。。。

我看的是项目SDKs那个目录的某个子目录下的clang，然后用./clang --version看的

**Comment by happyxianyu** [comment]
> 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> 
> 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> 
> （你是咋判断出是 14.0.0 的。。。

xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。

**Comment by waruqi** [comment]
> > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > （你是咋判断出是 14.0.0 的。。。
> 
> xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。

xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c

**Comment by happyxianyu** [comment]
> > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > （你是咋判断出是 14.0.0 的。。。
> > 
> > 
> > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> 
> xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c

--vs_sdkver=10.0.15063.0，你确定这个版本还有吗？我在vs安装器上查了一下没找到。

![image](https://github.com/SakuraEngine/SakuraEngine/assets/57778195/0e973dd5-8cf1-4304-b2f3-8148ea23ea3c)

还有生成工具集，是指这个吗？

![image](https://github.com/SakuraEngine/SakuraEngine/assets/57778195/3e1c8877-36a4-4f7a-bf05-368cd2da9d0a)

**Comment by waruqi** [comment]
> > > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > > （你是咋判断出是 14.0.0 的。。。
> > > 
> > > 
> > > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> > 
> > 
> > xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c
> 
> --vs_sdkver=10.0.15063.0，你确定这个版本还有吗？我在vs安装器上查了一下没找到。
> 
> ![image](https://user-images.githubusercontent.com/57778195/268426510-0e973dd5-8cf1-4304-b2f3-8148ea23ea3c.png)
> 
> 还有生成工具集，是指这个吗？
> 
> ![image](https://user-images.githubusercontent.com/57778195/268426593-3e1c8877-36a4-4f7a-bf05-368cd2da9d0a.png)

我只是举例用法和格式，不要照搬，自己调整

**Comment by happyxianyu** [comment]
> > > > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > > > （你是咋判断出是 14.0.0 的。。。
> > > > 
> > > > 
> > > > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> > > 
> > > 
> > > xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c
> > 
> > 
> > --vs_sdkver=10.0.15063.0，你确定这个版本还有吗？我在vs安装器上查了一下没找到。
> > ![image](https://user-images.githubusercontent.com/57778195/268426510-0e973dd5-8cf1-4304-b2f3-8148ea23ea3c.png)
> > 还有生成工具集，是指这个吗？
> > ![image](https://user-images.githubusercontent.com/57778195/268426593-3e1c8877-36a4-4f7a-bf05-368cd2da9d0a.png)
> 
> 我只是举例用法和格式，不要照搬，自己调整

哦，我以为是你使用的环境，请问你使用的环境是什么呢？要解决MSVC工具链版本一致性问题肯定至少要确定一个版本吧。

**Comment by SaeruHikari** [comment]
> > > > > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > > > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > > > > （你是咋判断出是 14.0.0 的。。。
> > > > > 
> > > > > 
> > > > > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> > > > 
> > > > 
> > > > xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c
> > > 
> > > 
> > > --vs_sdkver=10.0.15063.0，你确定这个版本还有吗？我在vs安装器上查了一下没找到。
> > > ![image](https://user-images.githubusercontent.com/57778195/268426510-0e973dd5-8cf1-4304-b2f3-8148ea23ea3c.png)
> > > 还有生成工具集，是指这个吗？
> > > ![image](https://user-images.githubusercontent.com/57778195/268426593-3e1c8877-36a4-4f7a-bf05-368cd2da9d0a.png)
> > 
> > 
> > 我只是举例用法和格式，不要照搬，自己调整
> 
> 哦，我以为是你使用的环境，请问你使用的环境是什么呢？要解决MSVC工具链版本一致性问题肯定至少要确定一个版本吧。

其实是头文件版本有问题，STL 实现里面加了不该加的静态断言。按理说 C++20 这种早就稳定的版本，clang 10 开始就能稳定编译的，不应该随便改动 STL 实现，导致只有最新版本才能过编。你的应该是最新版本，基于你的版本往后退一个版本就可以了。

**Comment by happyxianyu** [comment]
> > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > （你是咋判断出是 14.0.0 的。。。
> > 
> > 
> > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> 
> xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c

xmake f --vs_toolset=14.2 -c -m debug

试了这个命令，但引用的头文件还总是14.3的。vs_toolset这个选项好像不生效💔，算了我放弃了。不过部分模块还是可用单独构建成功的。

**Comment by SaeruHikari** [comment]
这几天在忙没法改，明天我升级一下 libclang 暂时解决一下这个问题，后续再看看能不能独立带一份反射用的 STL 头。等升级 ok 我再来这个 issue 下通知你哈。

**Comment by SaeruHikari** [comment]
> > > > 这个是 meta 报错，现在用的是 15.0.0 的 clang sdk。
> > > > 升级应该也无法杜绝和本地 MSVC 工具链版本对不上的问题，微软最近更新破坏性都比较强，符号类和静态 assert 类的问题出过不少次了。这确实是个问题，可能要像 wasm toolchain 一样自带一份 C++ 头。我需要考虑一下怎么解决。
> > > > （你是咋判断出是 14.0.0 的。。。
> > > 
> > > 
> > > xmake构建支持指定MSVC工具链版本吗？或许可以考虑指定MSVC工具链版本。
> > 
> > 
> > xmake f --vs_toolset=14.0 --vs_sdkver=10.0.15063.0 -c
> 
> xmake f --vs_toolset=14.2 -c -m debug
> 
> 试了这个命令，但引用的头文件还总是14.3的。vs_toolset这个选项好像不生效💔，算了我放弃了。不过部分模块还是可用单独构建成功的。

又看了一下前文, 这个问题你应该回退 `vs_sdkver` 而不是 `vs_toolset`, 问题出在新版本 SDK 的头文件里。现在正在更新 `meta` 的 `libclang` 版本, 更新后应该就能在最新的 SDK 下工作了。

**Comment by SaeruHikari** [comment]
检查了一下问题出在 `MSVC STL` 里, 没办法做单独的头文件版本控制, 只能暂时升级 `libclang` 解决.

**Comment by SaeruHikari** [comment]
已修复
