### ISSUE TITLE
[Milestone] 0.1.0

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#13]
计划于明年年初释出 0.1.0 版本预览，在此 issue 下讨论届时会稳定可用的特性以及一些以有问题的改进方案。

**Comment by SaeruHikari** [comment]
API 需要重构，包含以下部分：

- I/O Service 部分比较混乱，尤其是牵扯到 DirectStorage 的情况下；
- RenderPass 的注册，实用中发现其注册顺序较为难以控制，因此需要改成每帧注册的形式；
- 从 RenderEffect 到 RenderPass 传递数据较为困难，需要添加一个传递用户数据的接口或重载参数；
- 在异步编程中，produce / peek drawcall 的接口产生了一些同步问题，即 produce 时还未加载完成但 peek 时完成了。这种竞争会导致用户代码产生潜在的错误，需要提供更加合理的接口来避免这种错误。

**Comment by SaeruHikari** [comment]
# entity name
可视化工具需要获取 entity 的显示名字，同时有一些需求也会涉及到 entity 的 name。需要实现一个类似虚幻 fname 的设施以及对应的组件。

**Comment by SaeruHikari** [comment]
延迟到年中六月

**Comment by SaeruHikari** [comment]
加入了更广泛的内容，继续延迟

**Comment by vkensou** [comment]
请问有支持subpass的计划吗？另外有可能将cgpu独立到一个项目中吗？

**Comment by SaeruHikari** [comment]
- 目前没有 mobile 的产品支持，并且考虑到 subpass 需要优化才能比较高效，所以 subpass 不在目前的 roadmap 里；
- 有，独立出库在短期计划内，今年年内会着手做这件事；
- 如果对 CGPU 和 subpass 有想法，可以开个新的 issue，我们后续做一些讨论、设计和支持。
