### ISSUE TITLE
[Runtime] Remove EASTL

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#138]
现在可序列化容器都有了内部实现，剩余的不可序列化容器，可以用 STL 进行替换。移除 EASTL 有助于保证更好的 C++ 标准一致性和外部兼容性，同时自实现容器也可以保证序列化容器的代码和布局可控性。

**Comment by SaeruHikari** [comment]
UMap 容器中 object_pools.cpp, TextureViewPool::erase
erase & 迭代器问题 @zhurongjun

**Comment by zhurongjun** [comment]
1. fixed array 实现
2. Span 与 Array 交接
3. add_or_assign

**Comment by zhurongjun** [comment]
1. front & back 的习惯保持

**Comment by zhurongjun** [comment]
fixed allocator，以及容器特定的 allocator 实现

**Comment by zhurongjun** [comment]
LRU cache

**Comment by SaeruHikari** [comment]
bitset

**Comment by zhurongjun** [comment]
LiteOptional 需要改善，另外 Lite 容器最好都在 base 中提供实现

**Comment by zhurongjun** [comment]
在 Allocator 内添加 zero_memory_for_pod，以兼容 STL 标准的 resize 行为

**Comment by zhurongjun** [comment]
命名规范化：Contain -> Contains

**Comment by zhurongjun** [comment]
- [x] 带 remove 功能的迭代器，以替代 erase 的功能（object_pools.cpp, TextureViewPool::erase）
- [x] Allocator 改造，容器特化 Allocator
- [x] FixedAllocator
- [x] UMap/USet 的 add_or_assign
- [x] front/back 与 push/pop 的习惯保持
- [x] 命名规范化 Contain -> Constains
- [x] BitSet
- [x] Optional（从 LiteOptional 改造）
- [x] 兼容 STL 标准的 resize 行为
- [x] LRU Cache
