### ISSUE TITLE
[Runtime] 容器返回未初始化DataRef的安全性设计

### ISSUE THREAD

**Issue by MaxwellGengYF** [SakuraEngine/SakuraEngine#152]
目前容器的接口设计如：
```
template <typename UK = MapKeyType, typename UV = MapValueType>
    requires(TransparentToOrSameAs<UK, typename Memory::MapKeyType, typename Memory::HasherType> &&
             std::convertible_to<UV, typename Memory::MapValueType>)
    DataRef add(UK&& key, UV&& value);
...
...
template <typename UK = MapKeyType>
    requires(TransparentToOrSameAs<UK, typename Memory::MapKeyType, typename Memory::HasherType>)
    DataRef try_add(UK&& key);
```
这里add返回的DataRef是已经初始化的值，而try_add则返回未初始化的引用，此时应该考虑未初始化值的解引用安全性设计，如：
```
template<typename T>
class UninitDataRef {
    friend class Map<T>;
    T *ptr;
    UninitDataRef(T *ptr) : ptr(ptr) {}
public:
    UninitDataRef(UninitDataRef const &) = delete;
    UninitDataRef(UninitDataRef &&rhs) = delete;

    ~UninitDataRef() {
#ifndef NDEBUG
        if (ptr) {
            log_error("Bad.");
        }
#endif
    }
    template<typename... Args>
        requires(std::is_constructible_v<T, Args && ...>)
    T &deref(Args &&...args) && {
        new (std::launder(ptr)) T{std::forward<Args>(args)...};
        auto p = ptr;
        ptr = nullptr;
        return *p;
    }
};
```

**Comment by SaeruHikari** [comment]
移除 ```try_add``` 接口来去除这个歧义，留用：
- ```try_emplace(k, args...)```：现代 STL 风格，传入参数进行可选值构造；
- ```try_add_unsafe(k)```：朴素容器风格，如果插入则为为初始化值；
- ```try_add_default(k)```：朴素容器风格，如果插入则为**默认值初始化值 [ new T() ]**;
    - 不会使用和考虑 C++ 标准定义的**默认初始化值 [ new T ]**;
- ```try_add_zeroed(k)```：朴素容器风格，如果插入则为 **memzero**;

**Comment by zhurongjun** [comment]
memory::construct 默认使用符合标准的构造方式，memory_traits::use_ctor 目前只控制是否能够使用 memset 直接置零。
波及的 API：
- Array::resize(n) -> Array::resize_default(n)
- RingBuffer::resize(n) -> Array::resize_default(n)
- SparseHashMap::try_add(k) -> SparseHashMap::try_add_default(k) 
- MultiSparseHashMap::add(k) -> MultiSparseHashMap::add_default(k)
