### ISSUE TITLE
[Runtime] 完善 ECS 销毁 API

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#157]

**Comment by BenzzzX** [comment]
ECS 销毁目前主要问题来自于 `chunk_view` 作为迭代器的不稳定性，解决方案如下：
1. 采用稳定的引用，也就是 entity id，对应提供接口 `sugoiS_destroy_entities`
2. 在迭代中标记，在框架内执行销毁逻辑维护好迭代器，对应提供接口 `sugoiS_destroy_in_query_if`
3. 批量销毁，对应提供接口 `sugoiS_destroy_in_query` 和 `sugoiS_destroy_all`
