### ISSUE TITLE
[BUG] vulkan validation error

### ISSUE THREAD

**Issue by runner0353** [SakuraEngine/SakuraEngine#162]
运行indexinstance 
    [90mIn CGPUAMDAGSSingleton::Get At D:\game\SakuraEngine\modules\runtime\src\cgpu\common\cgpu_ags.cpp:31[0m
[0mVUID-vkGetPhysicalDeviceFormatProperties-format-parameter(ERROR / SPEC): msgNum: 1256049554 - Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties(): format (1000054000) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)

**Comment by SaeruHikari** [comment]
你先将 `indexed-instance.c` 中 L341 的 enable_debug_layer 和 enable_gpu_based_validation 置为 false，看看能否运行。

看你的层版本应该是 `1.3.268.0`，我也装了一个，里面有 `VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG = 1000054000` 的 VkFormat 定义，而且运行没问题。这种验证层 bug 有的时候是因为被 WeGame 之类的软件抢了环境，比如这个这样： 

![image](https://github.com/SakuraEngine/SakuraEngine/assets/39457738/1d344392-dece-4a10-99c4-52ae6f914750)

可以搜关键字 `vulkan` 过滤一下 DEBUG CONSOLE 启动期间的日志看看是不是被别的软件偷梁换柱了。

**Comment by SaeruHikari** [comment]
这个从属于一个扩展 `VK_IMG_format_pvrtc`，可能你的设备不支持，我开个分支尝试修一下。

**Comment by SaeruHikari** [comment]
PR 了，拉取再检查一下。

**Comment by SaeruHikari** [comment]
> 这个从属于一个扩展 `VK_IMG_format_pvrtc`，可能你的设备不支持，我开个分支尝试修一下。

这个我也去检查了，非常非常老版本的 Vulkan 有一个枚举范围 `VK_FORMAT_BEGIN/END_RANGE`，当时验证层写代码会用这个进行实现。这种不考虑扩展的枚举是坏设计，所以 19 年的时候这个枚举就被干掉了。在这个时间之前的 SDK 是会有你这个报错的，所以你要考虑升级下驱动和 SDK 版本了。。。

**Comment by runner0353** [comment]
[0m[33m[1m[2024/1/13 18:22:45(135:797)][unknown(tid:10716)] Log.WARN: Vulkan validation layer: Validation Performance Warning: [ UNASSIGNED-BestPractices-vkBindMemory-small-dedicated-allocation ] | MessageID = 0xb3d4346b | vkBindImageMemory():  vkBindImageMemory(): : Trying to bind VkImage 0x2cfba2000000001c[] to a memory block which is fully consumed by the image. The required size of the allocation is 262144, but smaller images like this should be sub-allocated from larger memory blocks. (Current threshold is 1048576 bytes.)

    [90mIn VkUtil_DebugUtilsCallback At D:\game\SakuraEngine\modules\runtime\src\cgpu\vulkan\vulkan_utils.c:1080[0m
[0m[37m[2024/1/13 18:22:45(346:342)][unknown(tid:4140)] Log.TRACE: D3D12 descriptor heap type: CBV_SRV_UAV, increment size: 32, Total allocated: 8388608(bytes)
    [90mIn cgpu_create_device_d3d12 At D:\game\SakuraEngine\modules\runtime\src\cgpu\d3d12\cgpu_d3d12.cpp:234[0m
[0m[37m[2024/1/13 18:22:45(373:942)][unknown(tid:4140)] Log.TRACE: D3D12 descriptor heap type: SAMPLER, increment size: 32, Total allocated: 65536(bytes)
    [90mIn cgpu_create_device_d3d12 At D:\game\SakuraEngine\modules\runtime\src\cgpu\d3d12\cgpu_d3d12.cpp:234[0m
[0m[37m[2024/1/13 18:22:45(374:673)][unknown(tid:4140)] Log.TRACE: D3D12 descriptor heap type: RTV, increment size: 32, Total allocated: 2097152(bytes)
    [90mIn cgpu_create_device_d3d12 At D:\game\SakuraEngine\modules\runtime\src\cgpu\d3d12\cgpu_d3d12.cpp:234[0m
[0m[37m[2024/1/13 18:22:45(382:363)][unknown(tid:4140)] Log.TRACE: D3D12 descriptor heap type: DSV, increment size: 8, Total allocated: 524288(bytes)
    [90mIn cgpu_create_device_d3d12 At D:\game\SakuraEngine\modules\runtime\src\cgpu\d3d12\cgpu_d3d12.cpp:234[0m
[0mAssertion failed: bCreated && "Failed to Try to Create SwapChain! An existed swapchain might be destroyed!", file D:\game\SakuraEngine\modules\runtime\src\cgpu\d3d12\cgpu_d3d12.cpp, line 2022

**Comment by SaeruHikari** [comment]
交换链开不起来，现在看可能是两个地方有问题。
- 格式有问题。去看 L387，用的 `CGPU_FORMAT_R8G8B8A8_UNORM` 格式在远古设备上可能不支持，改成 `CGPU_FORMAT_B8G8R8A8_UNORM` 试试;
- 例子开的 900x900 的窗口尺寸过大，超过了你的屏幕尺寸，所以用 900 交换链开不出来。

**Comment by runner0353** [comment]
但是CGPUTileTexture 和CGPUTexture可以正常运行

**Comment by SaeruHikari** [comment]
> 但是CGPUTileTexture 和CGPUTexture可以正常运行

这样啊。draw indexed 这个 demo 唯一的区别是开了两个线程，开两个窗口，同时运行两个后端的测试例子。可能你的环境不允许两个窗口？

https://github.com/SakuraEngine/SakuraEngine/blob/dev/samples/cgpu/cgpu-basic/indexed-instance/indexed-instance.c#L571

改成这样单线程运行单后端代码试试。

**Comment by runner0353** [comment]
解决了
