### ISSUE TITLE
[Question] Example Game.exe 有问题 

### ISSUE THREAD

**Issue by runner0353** [SakuraEngine/SakuraEngine#164]
点了AsyncMesh  场景中还是只有cube, 没有加载Mesh.

**Comment by SaeruHikari** [comment]
需要烘焙资产产出需要的资源。没有烘焙资产就会加载失败，烘焙流程现在是有些小路径问题的，操作比较繁琐不好跑通。这种高度不稳定的特性现在随时有可能变化重写，也暂时没工夫写 README，没实际需求的话先放着吧。
