### ISSUE TITLE
[BUG] dual bugs

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#17]
- dualJ 存在 double free 问题
![~9GZTW5V4R1CL49N5@~WOA8](https://user-images.githubusercontent.com/39457738/187828396-91e026f7-3b9c-4ee6-b117-4cc8f7854fa1.png)

- 存在异常的耗时 Task 
![2IO_(9)ES20%
@OOOA$%5D](https://user-images.githubusercontent.com/39457738/187828354-5534699e-f62f-49b9-976a-e81392f936cf.png)

- 存在内存泄露
![9JX9LC39K80@S6$QFJTZ(EY](https://user-images.githubusercontent.com/39457738/187828341-d30be952-ab56-49ae-8436-327bfaa574e7.png)

**Comment by BenzzzX** [comment]
double free 是因为 task 的 post function 的原子性问题导致多次调用，现已修复

**Comment by SaeruHikari** [comment]
dualJ 里面有很多问题且 profile 出 FTL 的延迟和查找时间都很久，需要实现进一步的任务系统接口化和多后端（marl, etc.）实现以及测试。

**Comment by BenzzzX** [comment]
FTL 主线程离家出走的问题已修复

**Comment by BenzzzX** [comment]
目前在 System Sync Entry 中存在 “泄漏” 的情况，在不存在读写冲突的情况下，对应的 entry 不会产生 flush，则所有的同步 event 会在 entry 中产生堆积，需要使用 weak pointer 进行过期 event 的清扫。

**Comment by BenzzzX** [comment]
当前已经实现 weak pointer，使用 dualJ_gc 进行清扫
