### ISSUE TITLE
[求助]构建项目时报错

### ISSUE THREAD

**Issue by TheFlowCrash** [SakuraEngine/SakuraEngine#20]
[编译报错.txt](https://github.com/SakuraEngine/SakuraEngine/files/10147945/default.txt)

**Comment by TheFlowCrash** [comment]
重新尝试，出现了新的错误栈
[第二种报错.txt](https://github.com/SakuraEngine/SakuraEngine/files/10147956/default.txt)

**Comment by BenzzzX** [comment]
看起来像是 meta.exe 没有正确执行

**Comment by SaeruHikari** [comment]
> 重新尝试，出现了新的错误栈 [第二种报错.txt](https://github.com/SakuraEngine/SakuraEngine/files/10147956/default.txt)

第二个错误栈是他昨天写坏了，你得一下最新版本，再删除 ./build 和 ./SDKs 下面所有的 zip。然后 setup + build 一遍试试。

**Comment by TheFlowCrash** [comment]
> > 重新尝试，出现了新的错误栈 [第二种报错.txt](https://github.com/SakuraEngine/SakuraEngine/files/10147956/default.txt)
> 
> 第二个错误栈是他昨天写坏了，你得一下最新版本，再删除 ./build 和 ./SDKs 下面所有的 zip。然后 setup + build 一遍试试。

这个确实修复好了Q_Q 已经能build到70%+，不过似乎还有点问题
[ 70%]: cache compiling.debug modules\runtime\src\containers\build.containers.cpp
[ 70%]: cache compiling.debug modules\runtime\src\ecs\build.chunck.cpp
[ 70%]: cache compiling.debug modules\runtime\src\ecs\build.dispatch.cpp
[ 70%]: cache compiling.debug modules\runtime\src\ecs\build.utils.cpp
[ 72%]: cache compiling.debug modules\runtime\src\json\build.reader.cpp
[ 72%]: cache compiling.debug modules\runtime\src\json\build.writer.cpp
[ 72%]: cache compiling.debug modules\runtime\src\lua\build.skr_lua.cpp
[ 72%]: cache compiling.debug modules\runtime\src\module\build.module.cpp
[ 72%]: cache compiling.debug modules\runtime\src\platform\build.platform.cpp
[ 72%]: cache compiling.debug modules\runtime\src\resource\build.system.cpp
[ 72%]: cache compiling.debug modules\runtime\src\task\build.task.cpp
[ 72%]: cache compiling.debug modules\runtime\src\type\build.serde.cpp
[ 72%]: cache compiling.debug modules\runtime\src\type\build.types.cpp
error: build.vma.cpp
D:\RefProjects\SakuraEngine\modules\runtime\src\cgpu\vulkan\internal\vk_mem_alloc.h(130): fatal error C1083: 无法打开包括文件: “vulkan/vulkan.h”: No such file or directory

  > in modules\runtime\src\cgpu\build.vma.cpp

**Comment by SaeruHikari** [comment]
> D:\RefProjects\SakuraEngine\modules\runtime\src\cgpu\vulkan\internal\vk_mem_alloc.h(130): fatal error C1083: 无法打开包括文件: “vulkan/vulkan.h”: No such file or directory

删多了吧，SDKs 下面 zip 都删了就行了，你是不是把包含目录也删了。那里面有 vulkan 头文件。

**Comment by TheFlowCrash** [comment]
好像是我SDK不全导致的，我再看看

**Comment by TheFlowCrash** [comment]
![image](https://user-images.githubusercontent.com/76473857/205672511-0c5fe475-0497-4021-8491-9679b31172e8.png)
感谢大佬，终于成功了

**Comment by SaeruHikari** [comment]
ok~
