### ISSUE TITLE
编译失败，meta codegen 似乎有问题

### ISSUE THREAD

**Issue by sailing-innocent** [SakuraEngine/SakuraEngine#218]
dev branch 中 ea7b0ea128f3ce0d9997c71cb5b87dcd25ad5cb2 （应该是目前最新的commit) 看当前CI是炸的

codegen 过程里面python报错，查了一下meta codegen似乎生成了不符合json语法的意外东西，在codegen.py中未看到使用

![image](https://github.com/SakuraEngine/SakuraEngine/assets/109784585/4c1a97a7-c5fd-4ee2-8b60-c5e97c1f5d51)

**Comment by SaeruHikari** [comment]
炸是炸的 self-host 的机器，ci 是过的。dev 很久不动了，codegen 重构了不少，你换 v8 分支编吧。

**Comment by sailing-innocent** [comment]
> 炸是炸的 self-host 的机器，ci 是过的。dev 很久不动了，codegen 重构了不少，你换 v8 分支编吧。

good, v8分支msvc是能编过的
