### ISSUE TITLE
[Runtime] Log

### ISSUE THREAD

**Issue by BenzzzX** [SakuraEngine/SakuraEngine#25]
当前的 log 实现功能功能弱、性能低，需要替换为一个更好的实现。至少有如下功能：
- 基础性能要求（不要求服务器 1g/s 那种级别）
- 日志 io 管理，包括文件，控制台，网络等
- category，group 等分组机制
- 基本的线程安全

**Comment by SaeruHikari** [comment]
接口沿用现在的并做一些扩展。
主流平台用 spdlog，非主流平台自己实现。

**Comment by BenzzzX** [comment]
https://github.com/odygrd/quill 这个看起来也很不错

**Comment by SaeruHikari** [comment]
看上去确实更合适，TLS 小缓冲的设计比较适合实时应用，延迟比较低。

**Comment by SaeruHikari** [comment]
quill 的代码写的很啰嗦，有一些莫名其妙的设计模式。仿照它的运行模式写一个实现。

**Comment by SaeruHikari** [comment]
写了一个初始版本实现，测得请求现场的返回速度确实有大幅的提升：
 
![5QJEB_KR%`IE7G65`)(IN)5](https://github.com/SakuraEngine/SakuraEngine/assets/39457738/b6ebebe1-2b2b-41df-a0dc-4ff2540b99ec)

![ZTO E`KWX(MB227HUKRMGKO](https://github.com/SakuraEngine/SakuraEngine/assets/39457738/7ff43c25-b3d8-45ca-9c46-2f775ad198d5)

接下来几天先做一版，比较完善的实现一下功能。包括这些：
- [x] 日志格式和颜色的处理，最好可以自定义；
- [x] 纳秒精度计时器 & 时间格式的处理；
- [x] Sink 的实现，以及提供自定义实现的接口；
  - [x] Console/DebugOutput Sink
  - [x] FileSink
  - [ ] GUI Console Sink (通过共享文件句柄显示 GUI，刷新 OS 控制台的成本太高) 
- [x] BackTrace;
- [ ] StackTrace； 
- [ ] 异常退出的处理，即使用各种 handler 处理程序的 `signal` 及 `exception`；
- [ ] 进一步的延迟优化，例如：
    - [ ] profile 中观测到最耗时的是堆对象创建，用 `arena` 优化请求现场的堆内存申请；
    - [x] `concurrent_queue` 优化为 TLS SPSC 或是添加生产者 token 优化；
    - [ ] ~~像 quill 一样加入 hot/cold 或 likely/unlikely 这样的预取优化；~~

StackTrace 等功能，转到 #78 处理程序异常和中断。
