### ISSUE TITLE
[Runtime] Input HAL

### ISSUE THREAD

**Issue by BenzzzX** [SakuraEngine/SakuraEngine#29]
当前 Input 的底层基于一个不再维护的库 GainInput，其实现比较脏乱。需要实现一个新的 Input 底层，同时支持基于网络的低延迟输入。

**Comment by SaeruHikari** [comment]
接口可以参照微软的 GameInput，该接口具有纯异步和低延迟的特点，适合 NextGen 的游戏。

**Comment by SaeruHikari** [comment]
[input module](https://github.com/SakuraEngine/SakuraEngine/tree/main/modules/input)

目前有简单的 GameInput 和 SDL2 后端。接下来替换 InputSystem 的原始实现并删除 GAInput。

**Comment by SaeruHikari** [comment]
PR #32 
基本实现了 InputSystem。

**Comment by SaeruHikari** [comment]
PR #33 
隔离了程序消息循环。
