### ISSUE TITLE
是否应该在README中说明下example的构建方式？

### ISSUE THREAD

**Issue by WeebOwO** [SakuraEngine/SakuraEngine#30]
是不是应该在文档中说明一下如何构建其他的example，因为在默认情况下生成的项目文件中只会生成application文件夹中的样例。如果想要生成其他的演示，还得自己手动传入xmake的参数或者修改对应的xmake.lua脚本。🤔

**Comment by SaeruHikari** [comment]
可以，等忙完手头事情回来提交的时候顺便搞一下。

**Comment by WeebOwO** [comment]
好的，谢谢您的及时回复
PS: 如果有一天我能写出来这么牛的代码就好了 😭

**Comment by SaeruHikari** [comment]
已添加相关 README
