### ISSUE TITLE
[Enhancement] 更好地模块（插件）化

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#4]
## 问题
一开始为了快速链接，把功能和特性都堆在了 Runtime 里。但现在 Runtime 里堆特性太多，反而造成了一系列问题。
- Runtime 构建速度变慢。很多有 codegen 的代码 （如 resource、rtti等）被放到了 Runtime 中，显著拖慢了构建，这和初衷相悖了；
- 开发特性时经常出现各种冲突，比如某特性代码构建出现问题，整个 Runtime 的开发都会被卡住；
需要更好地模块化以及更好地模块管理功能支持。
- 为 Runtime 引入了一些复杂依赖，例如 grpc、grpcc、meta 等。

## 需求
- 审查现有的 Runtime 功能，把可以模块化的功能尽量移动到 /modules 下；
- 构建更好的模块管理器。实现模块描述文件、自动模块 API 宏定义以及全模块 Unite 编译；
- 彻底移除当前的 /include 和 /src 文件夹，只留下 /modules；

**Comment by BenzzzX** [comment]
考虑 UE 或者 Unity 的两层做法，一层是 module，一层是 package/plugin，当前目标是先实现 module，也就是构建系统相关的部分，包括构建依赖管理和动态链接和全链接切换。下一步再实现 plugin，实现纯运行时依赖，惰性加载，和多资源根路径等的功能。

**Comment by Lu-Kye** [comment]
感觉可以考虑下是不是能只有plugin, runtime就是个特别极致干净的东西

**Comment by BenzzzX** [comment]
module 目前分为 runtime module 和 tool module，plugin 能够更好的打包这两者。

**Comment by Lu-Kye** [comment]
emmm 主要是针对一些特殊需求，假如有个客户只需要用engine做一个壁纸，然后如果modules中一旦有不需要的功能(physx, animation, .etc) 那基本上很难"动态“(不重新编译新的editor & runtime) 使最终导出的engine library 和 cpu 开销降到极致吧

**Comment by BenzzzX** [comment]
没看出来这个需求的动态性。

**Comment by SaeruHikari** [comment]
> emmm 主要是针对一些特殊需求，假如有个客户只需要用engine做一个壁纸，然后如果modules中一旦有不需要的功能(physx, animation, .etc) 那基本上很难"动态“(不重新编译新的editor & runtime) 使最终导出的engine library 和 cpu 开销降到极致吧

会有插件category和管理器设计，不需要的插件关掉就好了。

**Comment by SaeruHikari** [comment]
> emmm 主要是针对一些特殊需求，假如有个客户只需要用engine做一个壁纸，然后如果modules中一旦有不需要的功能(physx, animation, .etc) 那基本上很难"动态“(不重新编译新的editor & runtime) 使最终导出的engine library 和 cpu 开销降到极致吧

其实现在直接把gametool之类依赖usd的插件在xmake代码里关掉就可以编译最小runtime来用了。管理器只是会更好地分组以及生成开关代码。

**Comment by SaeruHikari** [comment]
现在在 xmake rules 中添加了一个 skr.module 的 [rule](https://github.com/SakuraEngine/Sakura.Runtime/commit/abe8c28aba854683cda5b287e539040a1c4d8b02)：
``` lua
 add_rules("skr.module", {api = "RUNTIME"})
```

此模块会自动决断 module 的 target kind  (shared or object)，并添加合适的预定义宏。通过设置 module_as_objects 可以使模块跳过 lib 归档或是 dll 链接，直接输出 objects，并最终全量链接到可执行程序中。

此外引擎的 SharedLibrary 类也被修改为可以读取进程本身的符号表，只需要为 load_library 传入路径 NULL 即可：

``` cpp
SharedLibrary processSymbolTable;
auto sucess = processSymbolTable.load(nullptr);
```

**Comment by SaeruHikari** [comment]
现在的 module 在运行时功能上已经没有问题，但嵌入到源码中的插件 JSON 描述需要被更好地处理。

``` cpp
IMPLEMENT_DYNAMIC_MODULE(SkrRenderGraphModule, SkrRenderGraph);
SKR_MODULE_METADATA(u8R"(
{
    "api" : "0.1.0",
    "name" : "SkrRenderGraph",
    "prettyname" : "SakuraRenderGraph",
    "version" : "0.0.1",
    "linking" : "shared",
    "dependencies" : [{"name":"SkrRT", "version":"0.1.0"}],
    "author" : "",
    "url" : "",
    "license" : "",
    "copyright" : ""
}
)",
SkrRenderGraph)
```

他们需要被移出源码，放入单独的描述文件中。此外，当前的插件不仅需要填写上述描述 JSON，还需要在 xmake 中被强依赖：

``` lua
target("SkrRenderGraph")
    add_rules("skr.module", {api = "SKR_RENDER_GRAPH"})
    add_deps("SkrRT") -- reference needed here
    add_includedirs("include", {public=true})
    add_files("src/*.cpp")
```

需要寻找一个实现弱依赖的方法。

目标：
- 可以在源代码以外更改描述文件；
- 移除 xmake 中的依赖代码，可以 xmake 解析 json 生成依赖列表，也可以提供独立程序解析 json 生成 xmake 命令，当然最好是实现弱依赖。

**Comment by SaeruHikari** [comment]
手动编写的 JSON 描述已经被移除，目前把依赖直接嵌入 xmake rule:

``` lua
shared_module("GameRT", "GAMERT", engine_version)
    set_group("04.examples/application")
    public_dependency("SkrRenderer", "0.1.0")
    public_dependency("SkrImGui", "0.1.0")
    public_dependency("SkrInputSystem", "0.1.0")
```

xmake 会在配置时自动生成模块元源文件:

``` cpp
#include "module/module.hpp"

SKR_MODULE_METADATA(u8R"__de___l___im__(
{
	"api": "0.1.0",
	"name": "GameRT",
	"prettyname": "GameRT",
	"version": "0.1.0",
	"linking": "shared",
	"author": "unknown",
	"url": "https://github.com/SakuraEngine/SakuraEngine",
	"license": "EngineDefault (MIT)",
	"copyright": "EngineDefault",
	"dependencies": [
 		{ "name":"SkrRenderer", "version": "0.1.0" },
		{ "name":"SkrImGui", "version": "0.1.0" },
		{ "name":"SkrInputSystem", "version": "0.1.0" }
	]
}
)__de___l___im__", GameRT)
```

**Comment by SaeruHikari** [comment]
模块基本已经达到 v0.1.0 的释出标准，关闭此 issue。后续还要做（带资源的） plugin 化封装。
