### ISSUE TITLE
[Runtime] ECS 的范式和封装

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#5]
目前面向数据编程主要使用的框架 DUAL 是非常贴近底层 Storage 的库。着重于性能，API 和细节非常繁琐，很难胜任实际开发中复杂的需求。需要考虑制定一套范式并提供对应的接口和实现（可以参考 FB 中的 Stream 等设计）。

- 要考虑同一逻辑时序上的多空间管理，降低实体复杂度的同时支持多副本等功能；
- 考虑静态组件（数据）和动态组件的分离，即将结构性稳定和易变的数据分别安置在不同的 DUAL 实体上，而 Access API 于更上层的实体代理中提供；
- 考虑序列化操作流，以实现重放等功能；
- 提供合理易用的 API，降低使用时的心智负担。

一个启示是不仅仅可以在单个 DUAL ENT 上组合 DUAL COMPs。或许可以组合多个 DUAL ENTs 来更加合理化内存布局。考虑到实际程序中，功能 Pass 往往和实体携带的数据类型组合强耦合，组合多个 Stream 而非杂乱地拼凑 COMP 会更加鲁棒且易用。Stream 中固定组合的 COMPS 会显著降低 Archetype 的复杂性，并显而易见地更加容易面向具体的实际功能进行调优。

**Comment by BenzzzX** [comment]
Stream 其实就是 Archetype，组合 Stream 就是将对象切割为多个，分布在多个 Archetype 中并以某种方式相互引用。这种做法可以更好的隔离各个系统，但是当设计对象间的交互会带来更复杂的同步问题；一般的设计是在性能没有极限要求的情况下，各个系统在内部进行并行，并在某个阶段在主线进行对象之间的信息交换。
