### ISSUE TITLE
macOS系统build失败

### ISSUE THREAD

**Issue by CS-Jackson** [SakuraEngine/SakuraEngine#57]
是带M1芯片的笔记本，是获取libboost-context.a时失败的。具体报错：
[ 33%]: archiving.release libboost-context.a
/Library/Developer/CommandLineTools/usr/bin/ar -cr build_a5b4e345/macosx/arm64/release/libboost-context.a
error: ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]

warning: ./xmake.lua:72: cannot match add_files("boost_context/asm/make_arm_sysv_macho_gas.S") in target(boost-context)
warning: ./xmake.lua:73: cannot match add_files("boost_context/asm/jump_arm_sysv_macho_gas.S") in target(boost-context)
error: execv(xmake build --verbose) failed(255)
  => install boost-context 0.1.0-skr .. failed
error: install failed!

和https://github.com/boostorg/context/issues/190不知道是否类似的问题。

**Comment by SaeruHikari** [comment]
mac arm 目前不支持，因为这个平台没有虚拟机，Actions 没有办法做 CI，必须本机。构建各种库都不方便，也无法维持构建质量，是暂时搁置的平台。尝试的话建议切换到 windows 先哈。
不过近期有产品规划要部署在 arm mac 上，metal3 和 arm mac 都是在今年 roadmap 上的。如果有需求或者兴趣的话可以持续关注哈。

**Comment by CS-Jackson** [comment]
感谢解答，期待各位巨巨支持。

**Comment by SaeruHikari** [comment]
关联 #59
