### ISSUE TITLE
帧内临时constant/vertex/index buffer用render graph管理是否粒度太细？

### ISSUE THREAD

**Issue by vkensou** [SakuraEngine/SakuraEngine#64]
render graph管理pass、texture和ssbo已经可以了，再管理这些写起来就太麻烦了。是否应该在commandbuffer/encoder里自动处理？
现在还没有material和mesh的概念？我感觉rendergraph之上应该是更粗粒度的概念，不应该太过细节。

**Comment by SaeruHikari** [comment]
材质没有实现完。
为什么资源这种纯 device 概念要牵扯到 command？因为 srp 有这样的 gfxdevice cmd 吗？那是带来大量性能障碍的错误的设计！
怎么算是临时，怎么算是持久？
srp 是建构在渲染器上的，我们是建构在 gfx 上的。你的这些疑惑是这些根源性差异带来的，你需要的这些东西也都是进一步软件封装提供的，而我们还没搭建到那个阶段。
同 #65

**Comment by SaeruHikari** [comment]
转到 #65
