### ISSUE TITLE
Render Graph是否应该添加RendererList的概念？

### ISSUE THREAD

**Issue by vkensou** [SakuraEngine/SakuraEngine#65]
我在Unity里用Render Graph有快两年了，我感觉Unity实现的RendererList概念十分好用。对图形程序员屏蔽了游戏对象遍历、cbuffer管理等细节，可以只专注于效果实现。
另外还有几个建议：
1. 加一个blit pass。只提供blit功能，类似unity里commandbuffer.blit。这种pass十分常用，我感觉大部分pass都是blit（移动端我是尽量少用compute pass）。
2. blit pass和compute pass的最后执行函数(dispatch/draw_fullscreen)可以由Render Graph自动执行，用户不需要/不能手动调用。
3. Render Graph之上应该粗粒度，不要把encoder直接暴露给用户，最好封装一下。

**Comment by SaeruHikari** [comment]
你 SRP 用多了。。。
- 1 的 blit pass 有例子里有。blit pass 的本质是基于平台和资源操作特征，启发性地调用 copy pass 或是 quad draw pass 或是 compute pass。SKR RG 的 pass 都是面向硬件队列的，而 blit pass 这是一个可软件封装的上层概念，随时可以在上层实现。
- 2 你提的这个 batch blit 的功能同样可以用户封装一个 delegate 列，在末尾注入；
- 3 RG 只是资源和状态追踪器，如果默认隐藏 gfx 功能，那我作为 gfx 程序员怎么精细控制？打个比方，我就需要在连续 dispatch 之间控制是否要引入 uav2uav barrier，这个隐藏了 encoder 咋办？
- 4 SRP 本就不是和 CGPU 一样高效的 API，SKR 的 RG 从根源概念上就和 Unity 提供的不完全一致。SRP 是低效的，他的封装也是受 GfxDevice Cmd 的固有限制设计的。但 CGPU 不一样，更何况实现他的接口，使用现在的 RG 完全可以基于外部 pass 实现，根本没有必要抹杀掉目前操作性更强的接口。
 
封装不是抹杀可控性强制降低复杂度，你说的这些功能是可以通过封装实现的，稳定的功能我们会提供封装，例如我们会提供函数辅助构建 imgui pass。

**Comment by SaeruHikari** [comment]
RendererList 是同样的道理，这部分牵扯场景结构所以会在未来重构。考虑到并发访问，目前在 pass 里访问 const prim view，未来的 list 封装自动转化为 view 即可。

现在项目还在非常早期的阶段，显然各种 scene 需要的 rendererlist 形式不尽相同，材质部分也没有完工。从全局考虑我们不过早提供封装，目前的 demo 是牺牲了易用性的，这也是出于未来更强的扩展性考虑。

**Comment by vkensou** [comment]
我的理解是RenderGraph就是一个编译器，图形API就是汇编。图形程序员在RenderGraph之上工作，相当于使用高级语言。我的建议可能更偏向于把RenderGraph的接口当成“Python/Lua”，尽可能易用，屏蔽掉细枝末节。可能你的理解是当成“C/C++”，尽可能保持可操控性。
Unity是有点封装过度了，而且它是基于opengl开发，概念更接近opengl。这个就不提了。
我是觉得想更好的推广的话，为了易用性是需要做一些妥协。
比如cbuffer、临时vertex/index buffer，可以由commandbuffer做临时管理。commandbuffer提交之后回收。这个用法我是Granite里学的，我感觉这样用起来比较简单。

**Comment by SaeruHikari** [comment]
- skr rg 是无 cmd 的。cmd 翻译会大幅度折损 drawcall 吞吐量。我们的 rg 有 transient resource，外部声明后资源池管理甚至 memory aliasing 已经是自动的了，还能咋自动？
- 资源混入 cmd 是错误的设计。这些是设备对象，跟 cmd list 和 queue 根本毫无关系。基于这样设计的系统渲染线程现场都会引入大量的卡顿，unity 和 4.22 前的 ue 就是如此。后续版本的 ue 就因为这个原因把资源操作逐渐移出了 cmd。
- 你说的 rg 是编译器这理论上对的，但你理解的 rg 是错误的。可以去看一下 frostbite 的分享，那是发明 rg 的团队。他们泄露的源码你也可以通过一定渠道找到看到，和 skr 的概念是近乎一致甚至更复杂的（他们有所谓的 move）。rg 隔离的是资源管理，同步和状态迁移，而不是实现一个渲染器。
- 你理解的利于推广同样是不对的，我们已经服务于多个项目，越是趋于专业的程序员就越是要求精密的操作性，并且至今关于易用性的问题少之又少，因为本身 rg 这项工件就是仅仅隔离同步和内存管理，关于资源句柄绑定我们也给出了很多语法糖。
- 同时我也很好奇你觉得哪里难用。如果你没法给出一个合理的 code sample 对比我觉得很难理解你的意思。在我看来你只是 srp 用多了，在既有的其他系统里反复寻找它的影子。

**Comment by vkensou** [comment]
可能我表达有误。cmd可以不用翻译，我只是习惯叫这个名字。我的意思是cmd可以包装一下底层的encoder，并且它可以带一些状态。反正cmd是临时的，pass执行完就释放/重置了。
举个例子，在我的实现里blitpass是一种特殊pass，其提供的cmd可以“录制”material和pass index（commandbuffer.SetMaterial(Material, int)  ），pass回调后自动执行blit fullscreen。还有computepass提供的cmd可以“录制”x/y/z thread num（commandbuffer.SetDispatchThread(int, int, int)），回调后自动执行dispatch。我这么设计的目的是防止用户在pass回调里手滑调用多次dispatch。当然这个只是口味问题可以不用纠结。
资源可以不混入cmd。我的意思是cbuffer之类的在pass中渲染现场临时申请，而不是在rendergraph上申请。
你说也对，可能我是习惯了unity的SetGlobalVector的接口，懒得自己手动管理cbuffer了。。。

我再举个例子：如果使用RendererList概念，RenderGraph的编译与RendererList收集可能是同时进行的，可能在DrawRendererList之前都不知道有多少物体需要渲染。这时就需要在pass执行的时候现场申请cbuffer之类的资源。
还有一个例子：比如某个物体逻辑上是世界里的一个普通物体，但它的网格是动态每帧在CPU端更新的。这时候的Unity里是这么做：Update里更新网格->rendergraph录制->pass执行（渲染物体 rendererlist）。这个逻辑下物体的网格的更新和它被渲染是解耦的。如果是skr里的rendergraph实现，可能应该是这样的：rendergraph录制（申请vbo/ibo）->pass执行（更新vbo/ibo，渲染物体），这样的话好像游戏逻辑和rendergraph耦合了。这个例子可能是我对skr理解不对，可以纠正我。

**Comment by vkensou** [comment]
我再说一下我的实践。除了需要RendererList的概念，还需要pass动态剔除的功能，比如某个RendererList为空则不执行该pass。有了剔除之后还需要资源回退，比如某pass被剔除了，但后面的pass还依赖它的输出，这时需要fallback到另一个资源上。
这里的剔除与基于present开始剔除DAG不一样。从present出发剔除，不存在pass被剔除但资源还被使用的情况。

还需要renderpass合并，如果多个相邻的renderpass的attachment完全一样，则这些pass自动合并，storeAction使用最后一个pass的。

**Comment by SaeruHikari** [comment]
所以你说的这些你自己分析完大都是都行，要么就是封装一下也能做到。。。rg 不负责渲染器行为，要加的话肯定是加外面哈。。。
现在没有封装就是因为这些都是渲染器行为，你也说了 renderlist 和材质啥的，那起码也是个 mesh pass 了。不同渲染器的上层设计是不一样的哈，不能在 rg 实现层硬怼这种结构。skr 后面 roadmap 会有 rt/pt 和 raster 两种管线，运行时材质和 mesh 都是不一样的，等到之后要分开封装提供，自然不能一把糊。

`还有computepass提供的cmd可以“录制”x/y/z thread num（commandbuffer.SetDispatchThread(int, int, int)），回调后自动执行dispatch。我这么设计的目的是防止用户在pass回调里手滑调用多次dispatch。`
这就是偏差的核心，根本不能这样简单抹 API，这不是 rg 的职责。
你咋知道用户不需要这样呢？他需要自己连续 dispatch 处理 uav2uav 甚至不放 uav barrier 重叠读写咋办（蒙皮和植被很常见的做法）？他需要 indirect dispatch 又咋办呢？

如果实在 get 不到这种思想，有个 CGPUXBindTable，可以任意地处理绑定合并，但他的做法不侵入 CGPU 或者 RG 实现，可以去看看品一下。

**Comment by vkensou** [comment]
indirect dispatch 就是再加一个接口：commandbuffer.SetDispatchIndrect()...
连续读写这个我没想到。你的意思是多次dispatch读写在同一个buffer的不同位置吗？这种用法我没用过，我用compute shader也不多，就不乱说了。。。
可能就是理解不同了，我是倾向于把RenderGraph当lua/python用。。。RenderGraph对外提供和依赖的都是高层次的抽象比如material、mesh、rendererlist之类。

我的理解里RenderGraph和RendererList是应该分开的。RenderGraph抽象层级更高，RendererList更低。RendererList要和场景物体组织方式、gpu buffer直接打交道。比如说RenderGraph只管先画depth only，后画opaque，不关心他是怎么画出来的、资源怎么申请管理。RendererList管怎么组织收集，比如不支持compute shader的，就cpu端job system剔除；支持compute shader，就compute shader cull，indirect draw（当然这里compute shader cull需要跟RenderGraph交互，在前面插入一个compute pass）；支持mesh shader就直接用mesh shader；再或者更传统的四叉树八叉树剔除等等。

**Comment by SaeruHikari** [comment]
`indirect dispatch 就是再加一个接口：commandbuffer.SetDispatchIndrect()...
连续读写这个我没想到。你的意思是多次dispatch读写在同一个buffer的不同位置吗？这种用法我没用过，我用compute shader也不多，就不乱说了。。。`
是你想的这样。而且不只是不同位置，还有可能是重叠位置，所以没那么简单的。加接口就更不考虑了，徒增复杂度和维护难度，从这个接口 dispatch 和从 encoder dispatch 没有任何区别还要写两次代码。

`我的理解里RenderGraph和RendererList是应该分开的。RenderGraph抽象层级更高，RendererList更低。RendererList要和场景物体组织方式、gpu buffer直接打交道。`
不同的渲染器，层级结构和加速结构压根不一样，GPU Scene 也可能不一样，根本就抽象不出所谓的万能 list，必须每个渲染器自己提供一个 draw 结构才行。比如静态网格可能是个 VB，但植被 IndirectDraw 就是个索引，要是类 Nanite 管线那就又变成一个页码，这咋能统一呢？

建议看下 frostbite 原分享哈，我跟你解释的已经蛮细了。UE 的也是 frostbite 的路子，也可以看。SRP 本身的问题也不是对标 OGL，而是它架设在 Unity 提供的渲染器上（这个渲染器还很落后），所以他的 RG 本身就很顶层。

**Comment by SaeruHikari** [comment]
你提到的很多东西，比如 blit pass，render list，这些都是后续会加的。但一定是架在高层渲染器的，绝不是侵入 rg 这种形式。
例如 indirect draw 可能有个进一步封装过的 indirect mesh pass，类 nanite 虚拟网格可能有个 virtual mesh pass。现在只是不过早去做这些事情，任何提前封装都是累赘。如果能做的话我自己早就做了，没有理由多写那么多字去堆 demo 哈。

**Comment by vkensou** [comment]
你说这个我想起来blit其实也有分viewport的多次draw的需求，不过我没这么用过。
