### ISSUE TITLE
[BuildSystem] CodeGen 相关规则需要改进

### ISSUE THREAD

**Issue by SaeruHikari** [SakuraEngine/SakuraEngine#79]
现在的代码生成走的是 xmake 的 `co_group`，并不是 `rule` 或者 `target`。这样效率上没问题，但是融入不了 xmake 的错误处理，经常出现构建失败需要删除 `build` 目录的问题。之前我尝试改进了构建系统中的代码生成，但是失败了。当时主要是因为：

- mako generateor 的概念不清晰，输入输出不明确，xmake 中获取不到足够的信息；
- 没有活用 target:clone() 这个功能，这个功能可以处理很多参数冲突；

现在这些问题已经改进，尝试搞一版，主要借鉴 xmake 内置的 Qt rules。

**Comment by SaeruHikari** [comment]
尝试了分离 target 的方案发现也很难实现，xmake 的 build-run 是一个整体，这种方法不符合 xmake 的思维模式。错误处理没法实现，主要还是因为那些头文件的构建没有计入 xmake 的 target build 中，导致的失败。所以接下来主要从这个角度出发，看看有没有什么方案可以把这些 co task 的执行流程反馈到 buildcmds 系统中。

**Comment by waruqi** [comment]
> 把这些 co task 的执行流程反馈到 buildcmds 系统中。

用 buildcmds 是不行的，那个是串行的，主要用于 project generator ，以及不关注并行的规则实现简化。。

想要高度并行，并且融合进来，得走 batchjobs 模式，构造任务图，会复杂点。。xmake 会根据构造的任务图依赖，尽可能并行编译，并且确保任务执行顺序

参考 https://github.com/xmake-io/xmake/blob/c801c64e8d272c61e5ee9967a87490ec9f51cfae/xmake/rules/protobuf/proto.lua#L194

https://github.com/xmake-io/xmake/blob/c801c64e8d272c61e5ee9967a87490ec9f51cfae/xmake/rules/protobuf/xmake.lua#L32
